#!/bin/bash

#
# Finds (and prints to stdout) all image files in SRC_FOLDER ($1) (and
# all its sub-folders recursively). Unless given, SRC_FOLDER defaults to
# the current directory ('.').
#
# @author mvz
#

SRC_FOLDER="$1"
if [[ "$SRC_FOLDER" == '' ]]; then
	SRC_FOLDER='.'
fi

find "$SRC_FOLDER" -exec file {} \; | grep -Eo '^(.+): \w+ image' | cut -d: -f1
