#!/bin/bash

#
# Executes 'git status -sb' for the given path.
#
# Call with option '-a' to print out the status no matter
# whether the repo is up-to-date or not.
#
# @author mvz
#

ALL_FLAG="$1" # can be '-a'
DIR="$2"

RED='\033[0;31m'
ORANGE='\033[0;33m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
GRAY='\033[1;30m'
NO_COLOR='\033[0m'

if [[ "$ALL_FLAG" != '-a' ]]; then
	# If first argument is not the 'all flag' ('-a') then it has to be the path
	ALL_FLAG=""
	DIR="$1"
	if [[ "$DIR" == '' ]]; then
		DIR="$2"
	fi
fi

if [[ "${DIR}" == "" ]]; then
	DIR="."
fi
if [[ "$DIR" == *.git ]]; then
	DIR="`dirname "$DIR"`"
fi

cd "$DIR"

# Uncomment the next line to fetch from all of your configured remotes (but not merge any changes in)
#git fetch --all

GIT_STATUS_RESULT="$(git status -sb)"
LOCAL_COMMITS="$(echo "${GIT_STATUS_RESULT}" | tail -n +2)"

HAS_UPSTREAM_BRANCH=false
HAS_COMMITS_ON_ANY_BRANCH_NOT_YET_PUSHED=false
UPSTREAM_IS_AHEAD=false

# Check whether there is an upstream branch
if [[ "${GIT_STATUS_RESULT}" == *"..."* ]]; then
	HAS_UPSTREAM_BRANCH=true
	# ... and, if so, check whether there are commits on any branch not yet pushed
	[ -z "$(git log --branches --not --remotes)" ] || HAS_COMMITS_ON_ANY_BRANCH_NOT_YET_PUSHED=true
	# ... and check whether origin is ahead (there are upstream commits not yet pulled)
	if [[ "${GIT_STATUS_RESULT}" == *"behind"* ]]; then
		UPSTREAM_IS_AHEAD=true
	fi
fi

if [[ "$LOCAL_COMMITS" != "" || "$ALL_FLAG" == "-a" || $HAS_COMMITS_ON_ANY_BRANCH_NOT_YET_PUSHED == true || $UPSTREAM_IS_AHEAD == true ]]; then
	printf "$(pwd)    "

	if [[ $HAS_COMMITS_ON_ANY_BRANCH_NOT_YET_PUSHED == true ]]; then
		printf "${ORANGE}unpushed commits${NO_COLOR}"
	elif [[ $HAS_UPSTREAM_BRANCH == true ]]; then
		printf "${GREEN}all commits pushed${NO_COLOR}"
	elif [[ $HAS_UPSTREAM_BRANCH == false ]]; then
		printf "${BLUE}no upstream${NO_COLOR}"
	fi

	if [[ $UPSTREAM_IS_AHEAD == true ]]; then
		printf "    "
		printf "${ORANGE}upstream is ahead${NO_COLOR}"
	fi

	printf "\n"

	if [[ "$LOCAL_COMMITS" != "" ]]; then
		printf "${RED}$LOCAL_COMMITS${NO_COLOR}\n"
	else
		printf "${GREEN}Up-to-date${NO_COLOR}\n"
	fi

	printf "${GRAY}----------------------------------------------------------------------------------------------------------${NO_COLOR}\n"
fi
