#!/bin/bash

#
# Recursively executes 'git_cllu' for the given path.
#
# @author mvz
#

DIR="$1"

if [[ "${DIR}" == "" ]]; then
	DIR="."
fi

find "${DIR}" -type d -name ".git" -print0 | xargs -0 -I "$[THE_REPO]" git_cllu "$[THE_REPO]/.."
