#!/bin/bash

#
# Executes 'git status --porcelain' for the given path.
#
# Call with option '-a' to print out the status no matter
# whether the repo is up-to-date or not.
#
# @author mvz
#

ALL_FLAG="$1" # can be '-a'
DIR="$2"

RED='\033[0;31m'
ORANGE='\033[0;33m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NO_COLOR='\033[0m'

if [[ "$ALL_FLAG" != '-a' ]]; then
	# If first argument is not the 'all flag' ('-a') then it has to be the path
	ALL_FLAG=""
	DIR="$1"
	if [[ "$DIR" == '' ]]; then
		DIR="$2"
	fi
fi

if [[ "${DIR}" == "" ]]; then
	DIR="."
fi
if [[ "$DIR" == *.git ]]; then
	DIR="`dirname "$DIR"`"
fi

cd "$DIR"
STATUS=`git status --short`

HAS_COMMITS_ON_ANY_BRANCH_NOT_YET_PUSHED=false
HAS_UPSTREAM_BRANCH=false
# Check whether there is an upstream branch
if [[ "$(git status -sb)" == *"origin"* ]]; then
	HAS_UPSTREAM_BRANCH=true
	# ... and if so, check whether there are commits on any branch not yet pushed
	[ -z "$(git log --branches --not --remotes)" ] || HAS_COMMITS_ON_ANY_BRANCH_NOT_YET_PUSHED=true
fi

if [[ "$STATUS" != "" || "$ALL_FLAG" == "-a" || $HAS_COMMITS_ON_ANY_BRANCH_NOT_YET_PUSHED == true ]]; then
	printf "$(pwd)    "
	if [[ $HAS_COMMITS_ON_ANY_BRANCH_NOT_YET_PUSHED == true ]]; then
		printf "${ORANGE}unpushed${NO_COLOR}"
	elif [[ $HAS_UPSTREAM_BRANCH == true ]]; then
		printf "${GREEN}all pushed${NO_COLOR}"
	elif [[ $HAS_UPSTREAM_BRANCH == false ]]; then
		printf "${BLUE}no upstream${NO_COLOR}"
	fi
	printf "\n"
	if [[ "$STATUS" != "" ]]; then
		printf "${RED}$STATUS${NO_COLOR}\n"
	else
		printf "${GREEN}Up-to-date${NO_COLOR}\n"
	fi
	echo "-------------------------------------------------------------"
fi
