#!/bin/bash

#
# Executes 'git config --list --local' (filtered by 'user.') for the
# given path.
#
# @author mvz
#

DIR="$1"

GREEN='\033[0;32m'
NO_COLOR='\033[0m'

if [[ "${DIR}" == "" ]]; then
	DIR="."
fi

cd "$DIR"
RESULT=$(git config --list --local | grep "^user.")

if [[ "${RESULT}" != "" ]]; then
	echo "`pwd`"
	printf "${GREEN}"
	echo "${RESULT}"
	printf "${NO_COLOR}"
	echo "-------------------------------------------------------------"
fi
