#!/bin/bash

#
# Returns 'true' if you are in a Git repo; 'false' otherwise.
#
# @author mvz
#

RESULT=$(git rev-parse --is-inside-work-tree 2> /dev/null)
if [ "$RESULT" == "true" ]; then
	echo "true"
else
	echo "false"
	exit 1
fi
