#!/bin/bash

#
# Finds and prints all files containing the specified string (regex) in
# the given folder and all sub folders recursively.
#
# If no folder is passed the current directory (".") and all its sub folders
# are searched.
#
# @author mvz
#

regex=${1}
path=${2:-"."}

echo "Searching for regexp /${regex}/ in directory ${path}"

grep -Rnwi ${path} -e "${regex}"
