#!/bin/bash

#
# Continuously generates passwords of the required length ($1).
# If no length is specified 18 digits is used.
#
# The second parameter ($2) defines the number of special characters
# that must be in the password. The default is 0.
#
# Stolen from Dirk Möbius, subsequently improved
# https://github.com/dmoebius/dmoebius-bin/blob/master/mkpasswords
#

LENGTH="$1"
SPECIAL_CHARS="$2"

if [[ "${LENGTH}" -eq '' ]]; then
	LENGTH=18
fi

if [[ "${SPECIAL_CHARS}" -eq '' ]]; then
	SPECIAL_CHARS=0
fi

while [ true ]; do
	mkpasswd -s "${SPECIAL_CHARS}" -l "${LENGTH}"
done
